### ISSUE TITLE
真机测试失败

### ISSUE THREAD

**Issue by CSX1991** [lintide/ApplePayDemo#1]
Payment request is invalid: check your entitlements
Connection to remote alert view service failed

**Comment by zhimeilrc** [comment]
请参照文档对 **Bundle ID** 和 *\* Merchant ID *\* 做相应的修改。

**Comment by Seaofbbs** [comment]
2016-02-24 10:23:11.952 PayDemo[2480:1201708] Woo! Can make payments!
2016-02-24 10:23:11.961 PayDemo[2480:1201708] This device cannot make payments.
2016-02-24 10:23:11.963 PayDemo[2480:1201708] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <ViewController: 0x135d41ef0>.'
**\* First throw call stack:
(0x18187d900 0x180eebf80 0x1868ed0e4 0x1868ef9c0 0x186669cec 0x10006e0fc 0x1865a7e50 0x1865a7dcc 0x18658fa88 0x1865a76e4 0x1865a7314 0x18659fe30 0x1865704cc 0x18656e794 0x181834efc 0x181834990 0x181832690 0x181761680 0x182c70088 0x1865d8d90 0x10006e58c 0x1813028b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Seaofbbs** [comment]
同为真机测试 ,已经做好MerchantID并配置, BundleID为对应生成的Distribution版的Providing Profile中的BundleID.  编译时 ,也没有任何问题, 但在点击按钮后,出现如上报错. 提示红条结束在Main.m中的argc, argv上......

**Comment by lilongcnc** [comment]
Seaofbbs,我倒是用的这个没有出现你那个情况

**Comment by lilongcnc** [comment]
我显示的最后录入完指纹之后总是进入 paymentAuthorizationViewControllerWillAuthorizePayment 这个回调方法.不知道是怎么回事?

**Comment by Seaofbbs** [comment]
回楼上,同样的demo,在模拟器测试倒是出来了支付页面,模拟器没有真实的卡,默认出来的卡号都是1234,没法验证实际效果.

**Comment by Seaofbbs** [comment]
主要是不知道自己真机错误在哪

**Comment by lilongcnc** [comment]
在真机上是否已经绑卡？2016-02-24 10:23:11.961 PayDemo[2480:1201708] This device cannot make payments.

**Comment by lintide** [comment]
@lilongcnc 在真机上是否已经绑卡？

**Comment by lilongcnc** [comment]
@lintide  绑定了.iphone6+ios9.2, 最后始终不进didAuthorizePayment:这个方法,试试进入paymentAuthorizationViewControllerWillAuthorizePayment

**Comment by lintide** [comment]
@lilongcnc 目前真机是回调 *_paymentAuthorizationViewControllerWillAuthorizePayment *_ 方法，在虚拟机可以运行。

**Comment by lilongcnc** [comment]
@lintide  意思真机上回调进入*\* paymentAuthorizationViewControllerWillAuthorizePayment**这个方法是正确的???但是不是要获取到**payment toaken**等等返回的数据吗?

对的,在虚拟机上就是可以进入payment方法的

**Comment by Seaofbbs** [comment]
测试了无论真机是否绑卡 都会有相同的报错

**Comment by Seaofbbs** [comment]
2016-02-24 15:32:26.084 ApplePayDemoForSwift[2629:1257124] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <ApplePayDemoForSwift.ViewController: 0x127da61e0>.'
弹出的支付信息页面怎么是nil呢?

**Comment by lintide** [comment]
已解决，请参考 #3
